// A place changes its material and type, not its navigation or reading order.
const base = {
  scheme: "dark",
  surface: "#172433",
  ink: "#edf2f7",
  muted: "#b6c6d6",
  line: "#506176",
  accent: "#d2e5f8",
  onAccent: "#182737",
  tint: "#243748",
  radius: "24px",
  controlRadius: "18px",
  cardRadius: "14px",
  display: "var(--font-bricolage), sans-serif",
  ui: "var(--font-manrope), sans-serif",
  label: "var(--font-manrope), sans-serif",
  body: "var(--font-manrope), sans-serif",
  controlSize: "12px",
  smallControlSize: "11px",
  navSize: "12px",
  headingSize: "32px",
  smallHeadingSize: "25px",
  closeHeadingSize: "26px",
  bodySize: "12px",
  weight: "500",
  italic: "normal",
  tracking: "-.035em",
  grain: "none",
  shadow: "0 8px 28px #00000020",
};

export const biomeSkins = {
  planet: { ...base, name: "The whole world" },
  studio: {
    ...base,
    name: "Warm minimal",
    scheme: "light",
    surface: "#f1eee6",
    ink: "#302f2a",
    muted: "#656259",
    line: "#c9c3b5",
    accent: "#635641",
    onAccent: "#fffaf0",
    tint: "#e5dfd3",
    radius: "24px",
    controlRadius: "22px",
    cardRadius: "16px",
  },
  projects: {
    ...base,
    name: "Developer studio",
    surface: "#090c12",
    ink: "#edf3ff",
    muted: "#a5b4ce",
    line: "#34465f",
    accent: "#80b4ff",
    onAccent: "#09172b",
    tint: "#15243b",
    radius: "4px",
    controlRadius: "5px",
    cardRadius: "6px",
    display: "var(--font-jetbrains), monospace",
    ui: "var(--font-jetbrains), monospace",
    label: "var(--font-jetbrains), monospace",
    body: "var(--font-jetbrains), monospace",
    controlSize: "11px",
    smallControlSize: "10px",
    navSize: "11px",
    headingSize: "28px",
    smallHeadingSize: "23px",
    closeHeadingSize: "24px",
    weight: "500",
    tracking: "-.055em",
    shadow: "0 8px 28px #00000024",
  },
  court: {
    ...base,
    name: "Analog hi-fi",
    surface: "#282320",
    ink: "#f5e8d2",
    muted: "#c9b89f",
    line: "#6d5c4d",
    accent: "#e8ad70",
    onAccent: "#352419",
    tint: "#3a3028",
    radius: "32px",
    controlRadius: "9px",
    cardRadius: "8px",
    display: "var(--font-fraunces), Georgia, serif",
    ui: "var(--font-fraunces), Georgia, serif",
    label: "var(--font-manrope), sans-serif",
    controlSize: "16px",
    smallControlSize: "14px",
    navSize: "16px",
    headingSize: "47px",
    smallHeadingSize: "33px",
    closeHeadingSize: "32px",
    weight: "650",
    italic: "italic",
    tracking: "-.035em",
    grain:
      "repeating-linear-gradient(0deg, #fff4de03 0 1px, transparent 1px 4px)",
    shadow:
      "inset 0 0 0 4px #332b24, inset 0 0 0 5px #6d5c4d66, 0 8px 28px #00000026",
  },
  trail: {
    ...base,
    name: "Trail journal",
    scheme: "light",
    surface: "#e4e7d7",
    ink: "#263a2d",
    muted: "#53624d",
    line: "#b0bba1",
    accent: "#3c563c",
    onAccent: "#f6f5e7",
    tint: "#d1d9c1",
    radius: "2px 18px 18px 2px",
    controlRadius: "3px 12px 4px 14px",
    cardRadius: "2px",
    display: "var(--font-caveat), cursive",
    ui: "var(--font-caveat), cursive",
    body: "var(--font-courier), monospace",
    label: "var(--font-courier), monospace",
    controlSize: "21px",
    smallControlSize: "19px",
    navSize: "22px",
    headingSize: "47px",
    smallHeadingSize: "35px",
    closeHeadingSize: "34px",
    weight: "600",
    tracking: "-.025em",
    grain:
      "repeating-linear-gradient(0deg, transparent 0 25px, #263a2d16 25px 26px)",
  },
  future: {
    ...base,
    name: "Ink & paper",
    scheme: "light",
    surface: "#f3eee2",
    ink: "#292b2b",
    muted: "#64625b",
    line: "#c6c0b4",
    accent: "#465d70",
    onAccent: "#faf7ee",
    tint: "#e6dfd1",
    radius: "3px",
    controlRadius: "3px",
    cardRadius: "3px",
    display: "var(--font-newsreader), Georgia, serif",
    ui: "var(--font-newsreader), Georgia, serif",
    label: "var(--font-manrope), sans-serif",
    body: "var(--font-newsreader), Georgia, serif",
    controlSize: "17px",
    smallControlSize: "15px",
    navSize: "17px",
    headingSize: "42px",
    smallHeadingSize: "31px",
    closeHeadingSize: "31px",
    bodySize: "16px",
    weight: "400",
    tracking: "-.025em",
    grain:
      "repeating-linear-gradient(0deg, #292b2b04 0 1px, transparent 1px 3px)",
    shadow: "0 2px 0 #c6c0b4, 0 8px 28px #00000015",
  },
};
biomeSkins.entertainment = biomeSkins.court;

export function biomeSkinStyle(biome) {
  const skin = biomeSkins[biome] || biomeSkins.planet;
  return Object.fromEntries(
    Object.entries(skin)
      .filter(([key]) => key !== "name")
      .map(([key, value]) => [
        `--skin-${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`,
        value,
      ]),
  );
}
