import { projectGallerySites } from "./project-town-layout.mjs";
import { campusView } from "./campus-layout.mjs";
import { courtViews } from "./court-layout.mjs";
import { bridgeView } from "./bay-bridge.mjs";
import { cityViews } from "./sf-views.mjs";
import { trailView } from "./valley-layout.mjs";
import { fieldnotesCameras } from "./fieldnotes-layout.mjs";
// Content and camera positions share the same coordinates as the visible objects.
export const placeStops = {
  studio: [
    {
      id: "desk",
      label: "The desk",
      position: [1.55, 2.75, 1.65],
      portrait: {
        position: [1.6, 2.8, 2.5],
        target: [-0.4, 1.13, -1],
        fov: 64,
      },
      target: [-0.5, 1.15, -1.1],
      content: "journey",
      prompt: "Building at Offseason",
      hint: "Personal wellness, with an AI agent alongside you.",
    },
    {
      id: "bookshelf",
      label: "On my desk",
      position: [-2.2, 1.8, 0.25],
      target: [-1.45, 1, -0.65],
      portrait: {
        position: [-2.05, 2.1, 0.65],
        target: [-1.43, 1, -0.65],
        fov: 53,
      },
      content: "about",
      prompt: "Meet the person behind the projects",
      hint: "Steve Jobs, by Walter Isaacson. Currently on my desk.",
    },
    {
      id: "walk",
      label: "Take a walk",
      content: "about",
      prompt: "The life around the work",
      hint: "Following your little wanderer, between home and play. Choose another view to leave the path.",
    },
    ...cityViews,
    {
      id: "bay",
      label: "Across the bay",
      ...bridgeView,
      content: "notes",
      prompt: "A little further out",
      hint: "An orange crossing from the city toward the trails. A small tribute to the Bay.",
    },
  ],
  projects: [
    {
      id: "workbench",
      label: "The workbench",
      position: [-6.6, 2.85, 14.9],
      target: [-7, 1.7, 10],
      portrait: { position: [-6.6, 3.1, 17], target: [-7, 1.4, 10] },
      content: "work",
      collection: "workbench",
      prompt: "The ideas between the bigger builds",
      hint: "Open a notebook, or explore the full workbench.",
    },
    {
      id: "mobile",
      label: "iPhone studio",
      position: [-8.5, 3.05, -4.4],
      portrait: {
        position: [-8.5, 3.9, -1.8],
        target: [-8.5, 1.75, -10.5],
        fov: 84,
      },
      target: [
        projectGallerySites.mobile.position[0],
        1.8,
        projectGallerySites.mobile.position[2],
      ],
      content: "work",
      collection: "mobile",
      prompt: "A few things made for your pocket",
      hint: "Aatram, SimSim, and learning to build for iPhone.",
    },
    {
      id: "hackathons",
      label: "Hackathon hall",
      position: [11.2, 3.45, -1.5],
      target: [
        projectGallerySites.hackathons.position[0],
        1.5,
        projectGallerySites.hackathons.position[2],
      ],
      content: "work",
      collection: "hackathons",
      prompt: "The ideas we built in a weekend",
      hint: "Devils Invent, three times. AZ Spark. Voxel51. Made with a team.",
    },
    {
      id: "ring",
      label: "The ring",
      ...campusView().overview,
      content: "work",
      collection: "mobile",
      prompt: "A courtyard for pocket experiments",
      hint: "Low glass, a continuous canopy, and a garden in the middle.",
    },
    {
      id: "campus",
      label: "Courtyard",
      ...campusView().court,
      content: "work",
      collection: "mobile",
      prompt: "Open the iPhone & iPad shelf",
      hint: "Aatram, SimSim, and learning SwiftUI.",
    },
    {
      id: "aether",
      label: "Aether",
      position: [-4.8, 2.2, 1.4],
      target: [-5, 1.9, -2.48],
      portrait: {
        position: [-4.9, 2.35, 1.4],
        target: [-5, 1.2, -2.48],
        fov: 78,
      },
      project: "aether",
      prompt: "The story behind Aether",
      hint: "One question can lead to more than one good idea.",
    },
    {
      id: "agentex",
      label: "Agentex",
      position: [0.2, 2.2, -1.2],
      target: [0, 1.9, -5.08],
      portrait: {
        position: [0.1, 2.35, -1.2],
        target: [0, 1.2, -5.08],
        fov: 78,
      },
      project: "agentex",
      prompt: "A resume that stays true to you",
      hint: "Try the choices on the display. Your facts stay yours.",
    },
    {
      id: "gitcue",
      label: "GitCue",
      position: [5.7, 2.2, 1.4],
      target: [5.5, 1.9, -2.48],
      portrait: {
        position: [5.6, 2.35, 1.4],
        target: [5.5, 1.2, -2.48],
        fov: 78,
      },
      project: "gitcue",
      prompt: "The story behind GitCue",
      hint: "Small tools that make room for the work itself.",
    },
    {
      id: "mesa",
      label: "Mesa",
      position: [-5.8, 2.2, 7],
      target: [-6, 1.9, 3.23],
      portrait: { position: [-5.9, 2.35, 7], target: [-6, 1.2, 3.23], fov: 78 },
      project: "mesa",
      prompt: "Local history, made explorable",
      hint: "Turn a page. Follow the museum experience from room to kiosk.",
    },
    {
      id: "csdna",
      label: "csDNA",
      position: [6.2, 2.2, 7],
      target: [6, 1.9, 3.12],
      portrait: { position: [6.1, 2.35, 7], target: [6, 1.2, 3.12], fov: 78 },
      project: "csdna",
      prompt: "Making microscopy easier to work with",
      hint: "Follow the points, then take a closer look at the groups.",
    },
    {
      id: "soda",
      label: "SoDA",
      position: [0.2, 2.2, 3.9],
      target: [0, 1.9, 7.78],
      portrait: { position: [0.1, 2.35, 3.9], target: [0, 1.2, 7.78], fov: 78 },
      project: "soda",
      prompt: "Building with a student community",
      hint: "Good tools make it easier for the next person to join in.",
    },
  ],
  entertainment: [
    {
      id: "listening",
      label: "Listening room",
      position: [1.8, 2.5, 4.7],
      target: [-2.3, 1.45, -1.8],
      portrait: {
        position: [-0.8, 2.25, 4],
        target: [-2.5, 1.65, -0.1],
      },
      content: "music",
      collection: "music",
      prompt: "Put a record on",
      hint: "My own track, v4. Made while trying music production.",
    },
    {
      id: "cinema",
      label: "Comfort cinema",
      position: [10, 3, 8],
      target: [9, 2, -1.5],
      portrait: { position: [9.2, 3.4, 8.5], target: [9, 1.7, -0.7], fov: 58 },
      content: "music",
      collection: "shows",
      prompt: "My comfort shows",
      hint: "No spoilers. I’ve probably seen this one before.",
    },
  ],
  court: [
    {
      id: "volleyball",
      label: "Volleyball",
      ...courtViews.volleyball,
      content: "about",
      prompt: "The 5–9 side of my life",
      hint: "A serve, a return, one more rally. Tap a player or use the serve button.",
    },
    {
      id: "badminton",
      label: "Badminton",
      ...courtViews.badminton,
      content: "about",
      prompt: "Always up for a game",
    },
    {
      id: "basketball",
      label: "Basketball",
      ...courtViews.basketball,
      content: "about",
      prompt: "A few ways I like to move",
      hint: "Dribble, gather, release. Tap a player to take the next shot.",
    },
  ],
  trail: [
    {
      id: "trailhead",
      label: "At the trailhead",
      position: [0.6, 1.7, 5.2],
      target: [2.7, 1.03, 1.25],
      portrait: { position: [0.6, 1.8, 6], target: [2.7, 0.95, 1.25] },
      content: "about",
      prompt: "Life beyond the screen",
      hint: "Badminton, dance, hiking, new cities. A few other sides of me.",
    },
    {
      id: "lake",
      label: "By the water",
      position: [-3, 2.3, 5],
      target: [-8, 0, -3],
      content: "notes",
      prompt: "Places I want to go",
    },
    {
      id: "overlook",
      label: "The overlook",
      ...trailView().overlook,
      content: "notes",
      prompt: "Through my lens",
      compact: true,
      hint: "A frame for the valley. The photography collection is still to come.",
    },
  ],
  future: [
    {
      id: "socials",
      label: "Around the internet",
      ...fieldnotesCameras.socials,
      content: "socials",
      prompt: "Socials & public work",
      hint: "GitHub for the code. LinkedIn for the conversations.",
    },
    {
      id: "writing",
      label: "The writing studio",
      ...fieldnotesCameras.writing,
      content: "writing",
      prompt: "What I want to share",
      hint: "Coming soon: stories about building, design, and learning.",
    },
    {
      id: "collaborate",
      label: "Pull up a chair",
      ...fieldnotesCameras.collaborate,
      content: "contact",
      prompt: "Let’s make something",
      hint: "A conversation is a good place to start.",
    },
  ],
};
